USE [Workbench 2.0]
GO

INSERT INTO [dbo].[CN_EX17]
           ([Direction]
           ,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location])
SELECT NULL
,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location]
FROM CH_EX_1_2_3
GO

INSERT INTO [dbo].[CN_EX17]
           ([Direction]
           ,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location])
SELECT NULL
,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location]
FROM CN_EX_4_5_6
GO

INSERT INTO [dbo].[CN_EX17]
           ([Direction]
           ,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location])
SELECT NULL
,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location]
FROM CN_EX_7_8_9
GO


INSERT INTO [dbo].[CN_EX17]
           ([Direction]
           ,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location])
SELECT NULL
,[key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Destination]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Final_Country_of_Destination]
           ,[Producer_s_City_Province]
           ,[Producer_s_Location]
FROM CN_EX_10_11_12
GO
  