USE [Workbench 2.0]
GO

INSERT INTO [dbo].[CN_IM17]
           ([key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Origin]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_CIF__US__]
           ,[CIF_Value__US__]
           ,[Country_of_Purchase]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Importer_s_City]
           ,[Importer_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Consumer_s_City_Province]
           ,[Consumer_s_Location]
           ,[Direction])
SELECT [key_row_id]
      ,[Declaration_Date]
      ,[Product_HS]
      ,[Description]
      ,[Country_of_Origin]
      ,[Unit_Type]
      ,[Quantity]
      ,[Unit_Value_CIF__US__]
      ,[CIF_Value__US__]
      ,[Country_of_Purchase]
      ,[Transport_Method]
      ,[Customs_District]
      ,[Importer_s_City]
      ,[Importer_s_Location]
      ,[Company_Type]
      ,[Trade_Regime]
      ,[Consumer_s_City_Province]
      ,[Consumer_s_Location]
      ,[Direction]
  FROM [dbo].[CHN_Im_1_2_3]
GO

INSERT INTO [dbo].[CN_IM17]
           ([key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Origin]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_CIF__US__]
           ,[CIF_Value__US__]
           ,[Country_of_Purchase]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Importer_s_City]
           ,[Importer_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Consumer_s_City_Province]
           ,[Consumer_s_Location]
           ,[Direction])
SELECT [key_row_id]
      ,[Declaration_Date]
      ,[Product_HS]
      ,[Description]
      ,[Country_of_Origin]
      ,[Unit_Type]
      ,[Quantity]
      ,[Unit_Value_CIF__US__]
      ,[CIF_Value__US__]
      ,[Country_of_Purchase]
      ,[Transport_Method]
      ,[Customs_District]
      ,[Importer_s_City]
      ,[Importer_s_Location]
      ,[Company_Type]
      ,[Trade_Regime]
      ,[Consumer_s_City_Province]
      ,[Consumer_s_Location]
      ,[Direction]
  FROM [dbo].[CN_IM_4_5_6]
GO

INSERT INTO [dbo].[CN_IM17]
           ([key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Origin]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_CIF__US__]
           ,[CIF_Value__US__]
           ,[Country_of_Purchase]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Importer_s_City]
           ,[Importer_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Consumer_s_City_Province]
           ,[Consumer_s_Location]
           ,[Direction])
SELECT [key_row_id]
      ,[Declaration_Date]
      ,[Product_HS]
      ,[Description]
      ,[Country_of_Origin]
      ,[Unit_Type]
      ,[Quantity]
      ,[Unit_Value_CIF__US__]
      ,[CIF_Value__US__]
      ,[Country_of_Purchase]
      ,[Transport_Method]
      ,[Customs_District]
      ,[Importer_s_City]
      ,[Importer_s_Location]
      ,[Company_Type]
      ,[Trade_Regime]
      ,[Consumer_s_City_Province]
      ,[Consumer_s_Location]
      ,[Direction]
  FROM [dbo].[CN_IM_7_8_9]
GO

INSERT INTO [dbo].[CN_IM17]
           ([key_row_id]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Country_of_Origin]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_CIF__US__]
           ,[CIF_Value__US__]
           ,[Country_of_Purchase]
           ,[Transport_Method]
           ,[Customs_District]
           ,[Importer_s_City]
           ,[Importer_s_Location]
           ,[Company_Type]
           ,[Trade_Regime]
           ,[Consumer_s_City_Province]
           ,[Consumer_s_Location]
           ,[Direction])
SELECT [key_row_id]
      ,[Declaration_Date]
      ,[Product_HS]
      ,[Description]
      ,[Country_of_Origin]
      ,[Unit_Type]
      ,[Quantity]
      ,[Unit_Value_CIF__US__]
      ,[CIF_Value__US__]
      ,[Country_of_Purchase]
      ,[Transport_Method]
      ,[Customs_District]
      ,[Importer_s_City]
      ,[Importer_s_Location]
      ,[Company_Type]
      ,[Trade_Regime]
      ,[Consumer_s_City_Province]
      ,[Consumer_s_Location]
      ,NULL
  FROM [dbo].[CN_IM_10_11_12]
