USE [Workbench 2.0]
GO

INSERT INTO [dbo].[CN_17_18]
           ([Direction]
           ,[Origin_Region]
           ,[Destination_Region]
           ,[C2C_Lane]
           ,[Origin_Country]
           ,[Destination_Country]
           ,[Origin_Cty_Code]
           ,[Destination_Cty_Code]
           ,[Customs_District]
           ,[Importer_s_City]
           ,[Importer_s_Location]
           ,[Exporter_s_City]
           ,[Exporter_s_Location]
           ,[Transport_Method]
           ,[Declaration_Date]
           ,[Product_HS]
           ,[Description]
           ,[Unit_Type]
           ,[Quantity]
           ,[Unit_Value_FOB__US__]
           ,[FOB_Value__US__]
           ,[Unit_Value_CIF__US__]
           ,[CIF_Value__US__]
           ,[Company_Type]
           ,[Trade_Regime])
SELECT [Direction]
      ,[Origin_Region]
      ,[Destination_Region]
	  ,NULL
      ,[Country_of_Origin]
      ,[Country_of_Destination]
      ,[Origin_Cty_Code]
      ,[Destination_Cty_Code]
      ,[Customs_District]
      ,[Importer_s_City]
      ,[Importer_s_Location]
      ,[Exporter_s_City]
      ,[Exporter_s_Location]
      ,[Transport_Method]
      ,[Declaration_Date]
      ,[Product_HS]
      ,[Description]
      ,[Unit_Type]
      ,[Quantity]
      ,[Unit_Value_FOB__US__]
      ,[FOB_Value__US__]
      ,[Unit_Value_CIF__US__]
      ,[CIF_Value__US__]
      ,[Company_Type]
      ,[Trade_Regime]
FROM [dbo].[CN_2018_YTD]
GO


