USE [Workbench 2.0]
GO

INSERT INTO [dbo].[CN_10_18YTD]
           ([Direction]
           ,[Declaration Date]
           ,[Product HS]
           ,[Description]
           ,[Country of Origin]
           ,[Country of Destination]
           ,[Unit Type]
           ,[Quantity]
           ,[Unit Value FOB (US$)]
           ,[FOB Value (US$)]
           ,[Unit Value CIF (US$)]
           ,[CIF Value (US$)]
           ,[Transport Method]
           ,[Customs District]
           ,[Importer큦 City]
           ,[Importer큦 Location]
           ,[Exporter큦 City]
           ,[Exporter큦 Location]
           ,[Company Type]
           ,[Trade Regime]
           ,[Final Country of Destination]
           ,[Producer큦 City Province]
           ,[Producer큦 Location]
           ,[Destination]
           ,[Origin]
           ,[Weight (kg)]
           ,[Unit Value]
           ,[Harmonized Transport Method]
           ,[corrected Unit Value]
           ,[corrected weight]
           ,[UPS Region]
           ,[Origin Region]
           ,[Destination Region]
           ,[C2C_Lane])
SELECT [Direction]
      ,[Declaration Date]
      ,[Product HS]
      ,[Description]
      ,[Country of Origin]
      ,[Country of Destination]
      ,[Unit Type]
      ,[Quantity]
      ,[Unit Value FOB (US$)]
      ,[FOB Value (US$)]
      ,[Unit Value CIF (US$)]
      ,[CIF Value (US$)]
      ,[Transport Method]
      ,[Customs District]
      ,[Importer큦 City]
      ,[Importer큦 Location]
      ,[Exporter큦 City]
      ,[Exporter큦 Location]
      ,[Company Type]
      ,[Trade Regime]
      ,[Final Country of Destination]
      ,[Producer큦 City Province]
      ,[Producer큦 Location]
      ,[Destination]
      ,[Origin]
      ,[Weight (kg)]
      ,[Unit Value]
      ,[Harmonized Transport Method]
      ,[corrected Unit Value]
      ,[corrected weight]
      ,[UPS Region]
      ,[Origin Region]
      ,[Destination Region]
      ,[C2C_Lane]
  FROM [dbo].[CN_10_16]

