 SELECT [R2R_Lane]
      ,[C2C_Lane]
      ,[A2A_Lane]
      ,[O_Reg]
      ,[D_Reg]
      ,[O_Cty]
      ,[D_Cty]
      ,[O_ctyreg]
      ,[D_ctyreg]
      ,[O_State]
      ,[D_State]
      ,[O_City]
      ,[D_City]
      ,[O_LCS_POD]
      ,[D_LCS_POD]
      ,[O_Apt]
      ,[D_Apt]
      ,[Vertical]
      ,[GCKM]
	  ,SUM(CASE WHEN [year] = '2012' THEN subshipments ELSE NULL END) AS [Ship_2012]
	  ,SUM(CASE WHEN [year] = '2013' THEN subshipments ELSE NULL END) AS [Ship_2013]
	   ,SUM(CASE WHEN [year] = '2014' THEN subshipments ELSE NULL END) AS [Ship_2014]
	 ,SUM(CASE WHEN [year] = '2015' THEN subshipments ELSE NULL END) AS [Ship_2015]
	,SUM(CASE WHEN [year] = '2016' THEN subshipments ELSE NULL END) AS [Ship_2016]
	,SUM(CASE WHEN [year] = '2017' THEN subshipments ELSE NULL END) AS [Ship_2017]
	 ,SUM(CASE WHEN [year] = '2018' THEN subshipments ELSE NULL END) AS [Ship_2018]
	 ,SUM(CASE WHEN [year] = '2019' THEN subshipments ELSE NULL END) AS [Ship_2019]
	  ,SUM(CASE WHEN [year] = '2020' THEN subshipments ELSE NULL END) AS [Ship_2020]
	  ,SUM(CASE WHEN [year] = '2012' THEN subweight ELSE NULL END) AS [Weight_2012]
	  ,SUM(CASE WHEN [year] = '2013' THEN subweight ELSE NULL END) AS [Weight_2013]
	   ,SUM(CASE WHEN [year] = '2014' THEN subweight ELSE NULL END) AS [Weight_2014]
	 ,SUM(CASE WHEN [year] = '2015' THEN subweight ELSE NULL END) AS [Weight_2015]
	,SUM(CASE WHEN [year] = '2016' THEN subweight ELSE NULL END) AS [Weight_2016]
	,SUM(CASE WHEN [year] = '2017' THEN subweight ELSE NULL END) AS [Weight_2017]
	 ,SUM(CASE WHEN [year] = '2018' THEN subweight ELSE NULL END) AS [Weight_2018]
	 ,SUM(CASE WHEN [year] = '2019' THEN subweight ELSE NULL END) AS [Weight_2019]
	  ,SUM(CASE WHEN [year] = '2020' THEN subweight ELSE NULL END) AS [Weight_2020]
	INTO Concept_4_Shipments_Weights_Table
FROM (
SELECT 
[R2R_Lane]
      ,[C2C_Lane]
      ,[A2A_Lane]
      ,[O_Reg]
      ,[D_Reg]
      ,[O_Cty]
      ,[D_Cty]
      ,[O_ctyreg]
      ,[D_ctyreg]
      ,[O_State]
      ,[D_State]
      ,[O_City]
      ,[D_City]
      ,[O_LCS_POD]
      ,[D_LCS_POD]
      ,[O_Apt]
      ,[D_Apt]
      ,[Vertical]
      ,[GCKM]
	  ,[Year] AS [year]
	  ,SUM([shipments]) AS subshipments
	  ,SUM([Kilos]) AS subweight
  FROM [WN_Segment_database].[dbo].[Concept_4_vOct-2016]
  GROUP BY [R2R_Lane]
      ,[C2C_Lane]
      ,[A2A_Lane]
      ,[O_Reg]
      ,[D_Reg]
      ,[O_Cty]
      ,[D_Cty]
      ,[O_ctyreg]
      ,[D_ctyreg]
      ,[O_State]
      ,[D_State]
      ,[O_City]
      ,[D_City]
      ,[O_LCS_POD]
      ,[D_LCS_POD]
      ,[O_Apt]
      ,[D_Apt]
      ,[Vertical]
      ,[GCKM]
	  ,[Year]
	  ) Sub
GROUP BY [R2R_Lane]
      ,[C2C_Lane]
      ,[A2A_Lane]
      ,[O_Reg]
      ,[D_Reg]
      ,[O_Cty]
      ,[D_Cty]
      ,[O_ctyreg]
      ,[D_ctyreg]
      ,[O_State]
      ,[D_State]
      ,[O_City]
      ,[D_City]
      ,[O_LCS_POD]
      ,[D_LCS_POD]
      ,[O_Apt]
      ,[D_Apt]
      ,[Vertical]
      ,[GCKM]